stateDiagram-v2
    [*] --> Still
    Still --> [*]
    Still --> Moving
    Moving --> Still
    Moving --> Crash
    Crash --> [*]
    Crash --> Hello_World
    Hello_World --> [*]
    Hey_There --> Hello_World
    Whats_Up --> Hey_There    
    Stupid --> DidItWork?
